-- ============================================================================
-- SUPERSeded by Migration 20: 1024d Matryoshka Embedding
-- ============================================================================
--
-- This migration is NO LONGER NEEDED.
--
-- ORIGINAL PURPOSE (now obsolete):
-- - Was intended to create an HNSW index on 4096d vectors after pgvector 0.8.4+
-- - ASSUMED pgvector 0.8.4 would lift the 2000d HNSW limit — IT DOESN'T EXIST.
--
-- WHAT HAPPENED INSTEAD (AD-24):
-- - pgvector 0.8.2 IS the latest stable (as of 2026-04-22)
-- - HNSW_MAX_DIM is hardcoded to 2000 in pgvector's hnsw.h
-- - IVFFlat has the same 2000d limit
-- - No version of pgvector supports HNSW at 4096d
--
-- SOLUTION ADOPTED:
-- - Migration 20: Switch to 1024d embeddings via MRL (Matryoshka Representation Learning)
-- - qwen3-embedding:8b supports /v1/embeddings with dimensions=1024
-- - 1024d < 2000d HNSW limit → index works perfectly
-- - Quality retention at 1024/4096 ≈ 95%+ for cosine similarity
--
-- This file is preserved for historical reference only. DO NOT execute.
-- ============================================================================

-- NO-OP: This migration is superseded by 20-migrate-to-1024d.sql
-- The HNSW index is now created on embedding_1024 (vector(1024)) directly.