/**
 * Draft Insight Generation from Patterns
 * Story 1.7: Automated Knowledge Curation
 * 
 * Generates draft insights from detected patterns.
 */

import { createInsight, type InsightRecord } from "../neo4j/queries/insert-insight";
import type { DetectedPattern } from "./pattern-detector";
import { formatTraceRef } from "../validation/trace-ref";

/**
 * Draft insight generated from a pattern
 */
export interface DraftInsight {
  /** Generated insight_id */
  insight_id: string;
  /** Group ID (tenant) */
  group_id: string;
  /** Human-readable content */
  content: string;
  /** Confidence score */
  confidence: number;
  /** Source trace reference */
  source_ref: string;
  /** Source pattern */
  source_pattern: DetectedPattern;
  /** Generation metadata */
  metadata: {
    generated_at: Date;
    generator: string;
    pattern_id: string;
    frequency: number;
    success_rate: number;
  };
}

/**
 * Insight generation options
 */
export interface InsightGenerationOptions {
  /** Minimum confidence to create draft */
  min_confidence?: number;
  /** Maximum drafts to generate */
  max_drafts?: number;
  /** Whether to include metadata in content */
  include_metadata?: boolean;
  /** Custom content template */
  content_template?: (pattern: DetectedPattern) => string;
}

/**
 * Generation error
 */
export class InsightGenerationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "InsightGenerationError";
  }
}

/**
 * Default options
 */
const DEFAULT_MIN_CONFIDENCE = 0.7;
const DEFAULT_MAX_DRAFTS = 10;
const DEFAULT_INCLUDE_METADATA = true;
const GENERATOR_NAME = "curator-agent";

/**
 * Default content template
 * Generates human-readable insight content from pattern
 */
function defaultContentTemplate(pattern: DetectedPattern): string {
  const successRate = Math.round(pattern.success_rate * 100);
  
  let content = `## Insight: ${pattern.event_type}\n\n`;
  content += `**Pattern:** ${pattern.event_type} events have a ${successRate}% success rate `;
  content += `(${pattern.frequency} occurrences).\n\n`;
  
  if (Object.keys(pattern.metadata_patterns).length > 0) {
    content += `**Common Metadata:**\n`;
    for (const [key, value] of Object.entries(pattern.metadata_patterns)) {
      content += `- ${key}: ${JSON.stringify(value)}\n`;
    }
    content += `\n`;
  }
  
  if (Object.keys(pattern.outcome_patterns).length > 0) {
    content += `**Common Outcomes:**\n`;
    for (const [key, value] of Object.entries(pattern.outcome_patterns)) {
      content += `- ${key}: ${JSON.stringify(value)}\n`;
    }
    content += `\n`;
  }
  
  if (pattern.agents.length > 0) {
    content += `**Agents:** ${pattern.agents.join(", ")}\n\n`;
  }
  
  content += `**First seen:** ${pattern.first_seen.toISOString()}\n`;
  content += `**Last seen:** ${pattern.last_seen.toISOString()}\n`;
  
  return content;
}

/**
 * Generate draft insights from detected patterns
 * 
 * @param patterns - Detected patterns
 * @param options - Generation options
 * @returns Array of draft insights (not yet stored)
 */
export function generateDraftInsights(
  patterns: DetectedPattern[],
  options: InsightGenerationOptions = {}
): DraftInsight[] {
  const minConfidence = options.min_confidence ?? DEFAULT_MIN_CONFIDENCE;
  const maxDrafts = options.max_drafts ?? DEFAULT_MAX_DRAFTS;
  const includeMetadata = options.include_metadata ?? DEFAULT_INCLUDE_METADATA;
  const contentTemplate = options.content_template ?? defaultContentTemplate;

  // Filter by confidence
  const qualifiedPatterns = patterns.filter((p) => p.confidence >= minConfidence);

  // Sort by confidence (highest first)
  const sortedPatterns = qualifiedPatterns.sort((a, b) => b.confidence - a.confidence);

  // Limit to max drafts
  const selectedPatterns = sortedPatterns.slice(0, maxDrafts);

  return selectedPatterns.map((pattern) => {
    // Generate unique insight_id
    const timestamp = Date.now();
    const insightId = `curated-${pattern.event_type}-${timestamp}`;

    // Generate content using template
    let content = contentTemplate(pattern);

    // Add metadata section if requested
    if (includeMetadata) {
      content += `\n---\n`;
      content += `*Generated by ${GENERATOR_NAME} at ${new Date().toISOString()}*\n`;
      content += `*Pattern frequency: ${pattern.frequency} | Success rate: ${Math.round(pattern.success_rate * 100)}%*\n`;
    }

    return {
      insight_id: insightId,
      group_id: pattern.group_id,
      content,
      confidence: pattern.confidence,
      source_ref: `pattern:${pattern.id}`,
      source_pattern: pattern,
      metadata: {
        generated_at: new Date(),
        generator: GENERATOR_NAME,
        pattern_id: pattern.id,
        frequency: pattern.frequency,
        success_rate: pattern.success_rate,
      },
    };
  });
}

/**
 * Create draft insights in Neo4j
 * Stores draft insights with status='pending_approval'
 * 
 * @param drafts - Draft insights to create
 * @returns Array of created insight records
 */
export async function createDraftInsights(
  drafts: DraftInsight[]
): Promise<InsightRecord[]> {
  const created: InsightRecord[] = [];

  for (const draft of drafts) {
    try {
      const insight = await createInsight({
        insight_id: draft.insight_id,
        group_id: draft.group_id,
        content: draft.content,
        confidence: draft.confidence,
        source_type: "promotion",
        source_ref: draft.source_ref,
        created_by: GENERATOR_NAME,
        metadata: draft.metadata,
      });

      created.push(insight);
    } catch (error) {
      // Log but continue with other drafts
      console.error(`Failed to create draft insight ${draft.insight_id}:`, error);
    }
  }

  return created;
}

/**
 * Generate insight summary for approval UI
 * Creates a concise summary of the draft insight
 * 
 * @param draft - Draft insight
 * @returns Summary string
 */
export function summarizeDraft(draft: DraftInsight): string {
  const pattern = draft.source_pattern;
  const successRate = Math.round(pattern.success_rate * 100);
  
  return `${pattern.event_type}: ${successRate}% success rate (${pattern.frequency} occurrences)`;
}

/**
 * Generate batch of draft insights from patterns
 * Convenience function that combines generation and creation
 * 
 * @param patterns - Detected patterns
 * @param options - Generation options
 * @returns Array of created draft insights
 */
export async function generateAndCreateDrafts(
  patterns: DetectedPattern[],
  options: InsightGenerationOptions = {}
): Promise<InsightRecord[]> {
  const drafts = generateDraftInsights(patterns, options);
  return createDraftInsights(drafts);
}

/**
 * Calculate estimated quality of draft insights
 * Useful for prioritizing human review
 * 
 * @param draft - Draft insight
 * @returns Quality score (0.0 - 1.0)
 */
export function calculateDraftQuality(draft: DraftInsight): number {
  const pattern = draft.source_pattern;
  
  let quality = draft.confidence;
  
  // Boost for higher frequency
  if (pattern.frequency >= 10) {
    quality = Math.min(1, quality + 0.05);
  }
  
  if (pattern.frequency >= 50) {
    quality = Math.min(1, quality + 0.05);
  }
  
  // Boost for presence of metadata patterns
  if (Object.keys(pattern.metadata_patterns).length > 0) {
    quality = Math.min(1, quality + 0.02);
  }
  
  // Boost for presence of outcome patterns
  if (Object.keys(pattern.outcome_patterns).length > 0) {
    quality = Math.min(1, quality + 0.02);
  }
  
  // Reduce for single agent (less diverse)
  if (pattern.agents.length === 1) {
    quality = Math.max(0.5, quality - 0.03);
  }
  
  // Boost for multiple agents (more generalizable)
  if (pattern.agents.length >= 3) {
    quality = Math.min(1, quality + 0.03);
  }
  
  return Math.round(quality * 100) / 100;
}

/**
 * Get curator statistics
 * Useful for monitoring curator performance
 * 
 * @param groupId - Group ID
 * @returns Statistics about curator activity
 */
export async function getCuratorStats(groupId: string): Promise<{
  drafts_created: number;
  drafts_pending: number;
  drafts_approved: number;
  drafts_rejected: number;
  avg_confidence: number;
  avg_quality: number;
}> {
  // This would query Neo4j for curator-generated insights
  // For now, return placeholder stats
  return {
    drafts_created: 0,
    drafts_pending: 0,
    drafts_approved: 0,
    drafts_rejected: 0,
    avg_confidence: 0,
    avg_quality: 0,
  };
}