import { describe, it, expect } from "vitest";
import {
  generateDraftInsights,
  createDraftInsights,
  summarizeDraft,
  calculateDraftQuality,
  type DraftInsight,
} from "./insight-generator";
import type { DetectedPattern } from "./pattern-detector";
import type { InsightRecord } from "../neo4j/queries/insert-insight";

describe("insight-generator", () => {
  // Sample patterns for testing
  const createMockPattern = (overrides: Partial<DetectedPattern> = {}): DetectedPattern => ({
    id: `pattern-test-${Date.now()}`,
    group_id: "test-group",
    event_type: "test-event",
    frequency: 10,
    success_rate: 0.9,
    metadata_patterns: { environment: "production" },
    outcome_patterns: { result: "success" },
    agents: ["agent-1", "agent-2"],
    first_seen: new Date("2024-01-01"),
    last_seen: new Date("2024-01-15"),
    confidence: 0.9,
    ...overrides,
  });

  // =========================================================================
  // generateDraftInsights Tests
  // =========================================================================

  describe("generateDraftInsights", () => {
    it("should generate drafts from patterns", () => {
      const patterns = [createMockPattern()];
      const drafts = generateDraftInsights(patterns);

      expect(drafts.length).toBe(1);
      expect(drafts[0].group_id).toBe("test-group");
      expect(drafts[0].confidence).toBe(0.9);
      expect(drafts[0].content).toContain("test-event");
    });

    it("should filter by minimum confidence", () => {
      const patterns = [
        createMockPattern({ confidence: 0.9 }),
        createMockPattern({ confidence: 0.5, event_type: "low-conf" }),
      ];

      const drafts = generateDraftInsights(patterns, { min_confidence: 0.7 });

      expect(drafts.length).toBe(1);
      expect(drafts[0].source_pattern.event_type).not.toBe("low-conf");
    });

    it("should limit to max_drafts", () => {
      const patterns = [
        createMockPattern({ event_type: "event-1" }),
        createMockPattern({ event_type: "event-2" }),
        createMockPattern({ event_type: "event-3" }),
      ];

      const drafts = generateDraftInsights(patterns, { max_drafts: 2 });

      expect(drafts.length).toBe(2);
    });

    it("should sort by confidence (highest first)", () => {
      const patterns = [
        createMockPattern({ confidence: 0.7, event_type: "medium" }),
        createMockPattern({ confidence: 0.9, event_type: "high" }),
        createMockPattern({ confidence: 0.5, event_type: "low" }),
      ];

      const drafts = generateDraftInsights(patterns, { max_drafts: 10, min_confidence: 0.4 });

      // All patterns should pass min_confidence=0.4
      expect(drafts.length).toBe(3);
      expect(drafts[0].source_pattern.event_type).toBe("high");
      expect(drafts[1].source_pattern.event_type).toBe("medium");
      expect(drafts[2].source_pattern.event_type).toBe("low");
    });

    it("should use custom content template", () => {
      const patterns = [createMockPattern()];
      const drafts = generateDraftInsights(patterns, {
        content_template: (p) => `Custom: ${p.event_type} (${p.frequency}x)`,
        include_metadata: false, // Disable metadata to test custom template only
      });

      expect(drafts[0].content).toBe("Custom: test-event (10x)");
    });

    it("should include metadata when enabled", () => {
      const patterns = [createMockPattern()];
      const drafts = generateDraftInsights(patterns, { include_metadata: true });

      expect(drafts[0].content).toContain("Generated by");
    });

    it("should exclude metadata when disabled", () => {
      const patterns = [createMockPattern()];
      const drafts = generateDraftInsights(patterns, { include_metadata: false });

      expect(drafts[0].content).not.toContain("Generated by");
    });
  });

  // =========================================================================
  // summarizeDraft Tests
  // =========================================================================

  describe("summarizeDraft", () => {
    it("should create concise summary", () => {
      const draft: DraftInsight = {
        insight_id: "test-1",
        group_id: "test-group",
        content: "Test content",
        confidence: 0.9,
        source_ref: "pattern:test",
        source_pattern: createMockPattern({
          event_type: "summary-test",
          frequency: 25,
          success_rate: 0.85,
        }),
        metadata: {
          generated_at: new Date(),
          generator: "curator-agent",
          pattern_id: "test",
          frequency: 25,
          success_rate: 0.85,
        },
      };

      const summary = summarizeDraft(draft);

      expect(summary).toContain("summary-test");
      expect(summary).toContain("85%");
      expect(summary).toContain("25");
    });
  });

  // =========================================================================
  // calculateDraftQuality Tests
  // =========================================================================

  describe("calculateDraftQuality", () => {
    it("should base quality on confidence", () => {
      const draft: DraftInsight = {
        insight_id: "test-1",
        group_id: "test-group",
        content: "Test",
        confidence: 0.8,
        source_ref: "pattern:test",
        source_pattern: createMockPattern({ confidence: 0.8, frequency: 5 }),
        metadata: {
          generated_at: new Date(),
          generator: "curator-agent",
          pattern_id: "test",
          frequency: 5,
          success_rate: 0.9,
        },
      };

      const quality = calculateDraftQuality(draft);
      expect(quality).toBeGreaterThanOrEqual(0.5);
      expect(quality).toBeLessThanOrEqual(1);
    });

    it("should boost for high frequency", () => {
      const lowFreqDraft: DraftInsight = {
        insight_id: "test-1",
        group_id: "test-group",
        content: "Test",
        confidence: 0.8,
        source_ref: "pattern:test",
        source_pattern: createMockPattern({ confidence: 0.8, frequency: 5 }),
        metadata: {
          generated_at: new Date(),
          generator: "curator-agent",
          pattern_id: "test",
          frequency: 5,
          success_rate: 0.9,
        },
      };

      const highFreqDraft: DraftInsight = {
        insight_id: "test-2",
        group_id: "test-group",
        content: "Test",
        confidence: 0.8,
        source_ref: "pattern:test",
        source_pattern: createMockPattern({ confidence: 0.8, frequency: 100 }),
        metadata: {
          generated_at: new Date(),
          generator: "curator-agent",
          pattern_id: "test",
          frequency: 100,
          success_rate: 0.9,
        },
      };

      const lowQuality = calculateDraftQuality(lowFreqDraft);
      const highQuality = calculateDraftQuality(highFreqDraft);

      expect(highQuality).toBeGreaterThan(lowQuality);
    });

    it("should boost for multiple agents", () => {
      const singleAgent: DraftInsight = {
        insight_id: "test-1",
        group_id: "test-group",
        content: "Test",
        confidence: 0.8,
        source_ref: "pattern:test",
        source_pattern: createMockPattern({ confidence: 0.8, agents: ["agent-1"] }),
        metadata: {
          generated_at: new Date(),
          generator: "curator-agent",
          pattern_id: "test",
          frequency: 10,
          success_rate: 0.9,
        },
      };

      const multiAgent: DraftInsight = {
        insight_id: "test-2",
        group_id: "test-group",
        content: "Test",
        confidence: 0.8,
        source_ref: "pattern:test",
        source_pattern: createMockPattern({
          confidence: 0.8,
          agents: ["agent-1", "agent-2", "agent-3"],
        }),
        metadata: {
          generated_at: new Date(),
          generator: "curator-agent",
          pattern_id: "test",
          frequency: 10,
          success_rate: 0.9,
        },
      };

      const singleQuality = calculateDraftQuality(singleAgent);
      const multiQuality = calculateDraftQuality(multiAgent);

      expect(multiQuality).toBeGreaterThan(singleQuality);
    });
  });

  // =========================================================================
  // Edge Cases Tests
  // =========================================================================

  describe("edge cases", () => {
    it("should handle empty patterns array", () => {
      const drafts = generateDraftInsights([]);
      expect(drafts).toHaveLength(0);
    });

    it("should handle patterns with no metadata", () => {
      const patterns = [createMockPattern({ metadata_patterns: {} })];
      const drafts = generateDraftInsights(patterns);

      expect(drafts).toHaveLength(1);
      expect(drafts[0].content).toBeDefined();
    });

    it("should handle patterns with no agents", () => {
      const patterns = [createMockPattern({ agents: [] })];
      const drafts = generateDraftInsights(patterns);

      expect(drafts).toHaveLength(1);
    });
  });
});